name: Zola on GitHub Pages

on: 
 push:
  branches:
   - main

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Generate Token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ secrets.GHA_APP_ID }}
        private_key: ${{ secrets.GHA_APP_KEY }}
    - name: Checkout main
      uses: actions/checkout@v4
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.18.0
      env:
        GITHUB_TOKEN: ${{ secrets.ZOLA_GITHUB_TOKEN }}
        OUT_DIR: "docs"
