on: [push, workflow_dispatch]
name: Build and deploy GH Pages
jobs:
  checkout:
    runs-on: [self-hosted, arch]
    steps:
      - name: checkout
        uses: actions/checkout@v4
  ci: 
    runs-on: [self-hosted, arch]
    steps:
      - name: ci
        run: just ci
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, arch]
    steps:
      - name: build_and_deploy
        run: just deploy
