name: Zola on GitHub Pages

on: 
 push:
  branches:
   - main

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Create Token
      id: create_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ secrets.GHA_APP_ID }}
        private_key: ${{ secrets.GHA_APP_KEY }}
    - name: Checkout main
      id: checkout_main
      uses: actions/checkout@v4
    - name: Build and deploy
      id: build_and_deploy
      uses: kisoku/zola-deploy-action@kisoku/default_branch
      env:
        GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
        BUILD_FLAGS: --base-url=https://kisoku.net --output-dir=docs --force
        OUT_DIR: "docs"
